### ISSUE TITLE
Allow re-use of CMP_CTX for further transactions

### ISSUE THREAD

**Issue by tpank** [mpeylo/cmpossl#101]
Enabling re-use of `CMP_CTX` for further transactions would be an efficiency and programming convenience improvement, avoiding to free and then re-initialize various components of the internal `CMP_CTX` structure components, which can be quite costly - just think of trust stores including CRLs.

To this end, one could introduce a function like in `CMP_CTX_reuse(CMP_CTX *ctx)`, 
which would for instance reset any `transactionID` and `validatedSrvCert` entries.

Reported by: DDvO

Original Ticket: [cmpforopenssl/feature-requests/47](https://sourceforge.net/p/cmpforopenssl/feature-requests/47)

**Comment by DDvO** [comment]
This has long been solved, see `int OSSL_CMP_CTX_reinit(OSSL_CMP_CTX *ctx)`
