### ISSUE TITLE
setting reqExtensions and subjectAltName depends on order

### ISSUE THREAD

**Issue by mpeylo** [mpeylo/cmpossl#109]
Looking at the code, it appears to be possible to call CMP_CTX_subjectAltName_push1() after CMP_CTX_set0_reqExtensions() if no SANs are in the reqExtensions - but it is not possible the other way around. Probably it should work in any order.

**Comment by DDvO** [comment]
Oops, right. I've just improved the checks in `CMP_CTX_set0_reqExtensions(ctx, exts)` to allow this in case `exts` do not include SANs. Fix is in branch `fix_109`.
