### ISSUE TITLE
Have default/example [cmp] section in openssl.cnf

### ISSUE THREAD

**Issue by mpeylo** [mpeylo/cmpossl#124]
apps/openssl.cnf gets installed - as example - into "-prefix"/ssl or "-openssldir" directory with make install. 

It should also contain (potentially commented out) CMP configuration options, for users to comfortably configure it for their needs.

**Comment by DDvO** [comment]
I've recently implemented this; see https://github.com/openssl/openssl/pull/11470/files#diff-8ce6aaad88b10ed2b3b4592fd5c8e03a
