### ISSUE TITLE
Prefix public API with OSSL_

### ISSUE THREAD

**Issue by mpeylo** [mpeylo/cmpossl#128]
During API Consolidation #46 all exported function names and global variables (probably there are none) need to be prefixed with OSSL_ as this is a requirement by the OpenSSL project.

Richard Levitte [commented](https://github.com/openssl/openssl/issues/5926):

> some time ago, we decided not to polute the namespace like we've done before. That means that any new public API need to have an OpenSSL specific prefix, either OSSL_ or OPENSSL_. See for example include/openssl/store.h. Older already established bundles of symbols get to keep their names as they are. This applies to all public or exported symbols, be it macros, function names, global variables, types, ... (exported symbols means non-static function names and global variable names, because they are public symbols in static libraries)
> To be clear, this does not apply to openssl sub-commands, or public header file names (they are already prefixed with openssl/)

**Comment by DDvO** [comment]
Basically done; to be reviewed and merged.
