### ISSUE TITLE
Remove all backwards compatibilty version switches for OpenSSL PR

### ISSUE THREAD

**Issue by mpeylo** [mpeylo/cmpossl#129]
For PR to OpenSSL Project, all version switches for backwards compatibility must be removed.

However, there needs to be a patch / branch available to allow for establishing simple backwards compatibility to allow users needing old versions to integrate updates to the CMP code.

Richard Levitte [commented](https://github.com/openssl/openssl/issues/5926):

> I noticed there are some OpenSSL version dependent stuff... this is quite understandable for a project that wants to adapt to multiple OpenSSL versions. However, a CMP PR will obviously only be considered for the next feature release, whichever that will be. Adaptation to older OpenSSL versions can simply be cleaned away.

**Comment by DDvO** [comment]
At least until our PR is merged we can keep our master branch with version switches and use a simple tool to generate source file variant specific for any needed OpenSSL revisions (where all references like `#if OPENSSL_VERSION_NUMBER < 0x10100000L` are resolved).
