### ISSUE TITLE
store/access test recipe specific data according to OpenSSL scheme

### ISSUE THREAD

**Issue by mpeylo** [mpeylo/cmpossl#130]
Need to store/access test recipe specific data according to the OpenSSL recommended scheme.

Richard Levitte [commented](https://github.com/openssl/openssl/issues/5926):

> A while ago, we started a scheme where test recipe specific data is stored in a directory parallell to the recipe itself and with almost the same name, see this explanation. Individual files can be reached with data_file("file.pem")... however, I noted that you want to pass the directory name to the test program, so I submitted a [PR for that express purpose](https://github.com/openssl/openssl/pull/5928)... all you'll need is to replace my $cmpdir=srctop_dir("test", "cmp-tests"); with my $cmpdir=data_dir(); in test/recipes/80-test_cmp_cli.t and git mv test/cmp-test test/recipes/80-test_cmp_cli_data

**Comment by DDvO** [comment]
Basically done; to be reviewed and merged.

**Comment by DDvO** [comment]
Done; to be reviewed and merged.
