### ISSUE TITLE
Issues Building on Windows - Question

### ISSUE THREAD

**Issue by mikejhathaway** [mpeylo/cmpossl#131]
Hi There,

Has anyone encountered issues building cmpossl on Windows?

I am following the steps from the WIki (https://github.com/mpeylo/cmpossl/wiki/Quick-Start) but hit run into the following:

    git clone https://github.com/mpeylo/cmpossl.git
    C:\source>"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat"
    C:\source>cd cmpossl
    C:\source\cmpossl>perl Configure VC-WIN32
    Configuring OpenSSL version 1.1.1-pre3-dev (0x10101003L) for VC-WIN32
    Using os-specific seed configuration
    Creating configdata.pm
    Creating makefile
    Linking with static variants of shared libraries is not supported in this configuration
     in Configurations\common.tmpl, fragment starting at line 767
    **********************************************************************
    ***                                                                ***
    ***   If you want to report a building issue, please include the   ***
    ***   output from this command:                                    ***
    ***                                                                ***
    ***     perl configdata.pm --dump                                  ***
    ***                                                                ***
    **********************************************************************
    C:\source\cmpossl>nmake
    Microsoft (R) Program Maintenance Utility Version 14.00.24210.0
    Copyright (C) Microsoft Corporation.  All rights reserved.
    
    NMAKE : fatal error U1073: don't know how to make 'crypto\include\internal\bn_conf.h'
    Stop.

I am using Visual Studio 2015, ActivePerl 5.24.3 and nasm 2.11.08, has anyone else encountered this issue or have I missed something obvious?

Thanks in advance

Michael

**Comment by mpeylo** [comment]
Hi,

Hmmm, while I've never built on Windows (@DDvO does), that doesn't look as that would come from the CMP code. 

Are you able to build "plain" OpenSSL from https://github.com/openssl/openssl using the instructions in https://github.com/openssl/openssl/blob/master/NOTES.WIN ?

BR,
Martin

**Comment by mikejhathaway** [comment]
Hi,

Thanks for the reply, I am able to build OpenSSL 1.1.0i-dev using these instructions: https://gist.github.com/terrillmoore/995421ea6171a9aa50552f6aa4be0998, however if I apply the same process to the distribution from the cmpossl project I get the errors above. 

Regards

Mike

**Comment by mpeylo** [comment]
Hi,

We're basing on the OpenSSL development master branch (last rebase on March 14th) - I speculate that there might be some issue that isn't in OpenSSL 1.1.0i-dev. Can you try to build with the HEAD of the [master branch](https://github.com/openssl/openssl)? If that'd work for you, then upstream might have fixed that in the meantime, and I would prioritize rebasing to that. 

If you're not depending on a specific OpenSSL version, then the [backporting instructions to 1.0.2](https://github.com/mpeylo/cmpossl/wiki/Build-CMP-for-OpenSSL-1.0.2) might help for the time being.

BR,
Martin

**Comment by DDvO** [comment]
I've been able to reproduce this issue, while I do not have the time for a thorough analysis right now.
Like Martin, I suspect some general OpenSSL build problem with VC, at least with the OpenSSL version 1.1.1-pre3-dev we are currently based on.

Note the warning/error message the call to `perl Configure VC-WIN32` yields:

> Linking with static variants of shared libraries is not supported in this configuration
>  in Configurations\common.tmpl, fragment starting at line 767

I suggest trying to add the 'no-shared' option when doing the `Configure` step, which helped for me.

Yet then I found that `apps/cmp.c` did not compile with VC any more due to some recent change of mine that requires two definitions from `unistd.h`, which is not available in native Windows builds.
I thus just added some compatibility declarations, so please use `git pull` before your next build.

**Comment by mikejhathaway** [comment]
Hi,

I can build the OpenSSL from the latest branch no issues, I cannot however backport using the instructions form https://github.com/mpeylo/cmpossl/wiki/Build-CMP-for-OpenSSL-1.0.2, I have been using the steps in https://github.com/my-devices/sdk/wiki/Building-OpenSSL-on-Windows to build and run into the following:

The following is the last output from the command:

    nmake -f ms\nt.mak

Which reports:

    .\crypto\cmp\cmp_lib.c(44): fatal error C1083: Cannot open include file: 'crypto/cryptlib.h': No such file or directory
    NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.EXE"' : return code '0x2'
    Stop.

I checked and the file does exist in the source, next when running:

    nmake -f ms\nt.mak install

This too fails:

    Microsoft (R) Program Maintenance Utility Version 14.00.24210.0
    Copyright (C) Microsoft Corporation.  All rights reserved.

    Building OpenSSL
        cl /Fotmp32\cmp_lib.obj  -Iinc32 -Itmp32 /MT /Ox /O2 /Ob2 -DOPENSSL_THREADS  -DDSO_WIN32 -W3 -Gs0 -Gy -nologo -DOPENSSL_SYSNAME_WIN32 -DWIN32_LEAN_AND_MEAN -DL_ENDIAN -DUNICODE -D_UNICODE -D_CRT_SECURE_NO_DEPRECATE -DOPENSSL_NO_RC5 -DOPENSSL_NO_MD2 -DOPENSSL_NO_SSL2 -DOPENSSL_NO_KRB5 -DOPENSSL_NO_JPAKE -DOPENSSL_NO_WEAK_SSL_CIPHERS -DOPENSSL_NO_DYNAMIC_ENGINE /Zl /Zi /Fdtmp32/lib -c .\crypto\cmp\cmp_lib.c
    cmp_lib.c
    .\crypto\cmp\cmp_lib.c(44): fatal error C1083: Cannot open include file: 'crypto/cryptlib.h': No such file or directory
    NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.EXE"' : return code '0x2'
    Stop.

I don't need to use a specific version of OpenSSL so am flexible here.

Suggestions welcome?

Mike

**Comment by mikejhathaway** [comment]
Hi DDvO,

Sorry I missed your reply, thanks.

I tried a fresh pull and used the 'no-shared' option when doing the Configure step, nmake now runs but nmake test results in the following:

    C:\work\cmpossl>nmake test

    Microsoft (R) Program Maintenance Utility Version 14.00.24210.0
    Copyright (C) Microsoft Corporation.  All rights reserved.

            "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\nmake.exe" /                   depend && "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\nmake.exe" /                   _tests

    Microsoft (R) Program Maintenance Utility Version 14.00.24210.0
    Copyright (C) Microsoft Corporation.  All rights reserved.


    Microsoft (R) Program Maintenance Utility Version 14.00.24210.0
    Copyright (C) Microsoft Corporation.  All rights reserved.

    makefile(15761) : fatal error U1033: syntax error : ':' unexpected
    Stop.
    NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\nmake.exe"' : return code '0x2'
    Stop.

Regards

Mike

**Comment by mpeylo** [comment]
Hi,

I did a rebase to the latest openssl master - you can find it in cmp-rebased-2018-04-23

I hope (but cannot confirm) that this might fix the issue. After you have confirmed, I would move this over the current "cmp" branch.

Cheers,
Martin

**Comment by mikejhathaway** [comment]
Hi Martin,

Thanks, I ran the configure command with the 'no share' option as below

    perl Configure VC-WIN64A --prefix=c:\tools\OpenSSL\vc-win64a --openssldir=c:\tools\OpenSSL\SSL no-asm no-shared

'make' now works but 'nmake test' ends with the following

    Test Summary Report
    -------------------
    test\recipes\03-test_internal_cmp.t           (Wstat: 256 Tests: 1 Failed: 1)
      Failed test:  1
      Non-zero exit status: 1
    test\recipes\65-test_cmp_lib.t                (Wstat: 256 Tests: 1 Failed: 1)
      Failed test:  1
      Non-zero exit status: 1
    test\recipes\65-test_cmp_msg.t                (Wstat: 256 Tests: 1 Failed: 1)
      Failed test:  1
      Non-zero exit status: 1
    test\recipes\65-test_cmp_vfy.t                (Wstat: 256 Tests: 1 Failed: 1)
      Failed test:  1
      Non-zero exit status: 1
    Files=153, Tests=1145, 380 wallclock secs ( 1.17 usr +  0.28 sys =  1.45 CPU)
    Result: FAIL
    NMAKE : fatal error U1077: 'C:\Perl64\bin\perl.exe' : return code '0x1'
    Stop.
    NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\nmake.exe"' : return code '0x2'
    Stop.

Hope this helps?

Mike

**Comment by DDvO** [comment]
Hi Mike,

thanks for your further feedback.
Pleased that the build now works for you.

Unfortunately, the CMP unit tests do not (yet) work with binaries produced with VC. This is a known issue.´` 
Hope you do not actually depend on successfully using `nmake test`.

Regards,
  David

**Comment by DDvO** [comment]
@mpeylo, it looks like the rebase did not actually solve the original issue.
I'll investigate what the actual problem is (for which the `no-shared` option can be used as workaround).

**Comment by mikejhathaway** [comment]
Many Thanks, I can not get the build working and openssl.exe now runs, will see if the CMP client works tomorrow, one thing I just noticed is from this build the following is created in the openssl\bin directory:

    c_rehash.pl
    openssl.exe
    openssl.pdb

Vs OpenSSL 1.1.1

    c_rehash.pl
    libcrypto-1_1-x64.dll
    libcrypto-1_1-x64.pdb
    libssl-1_1-x64.dll
    libssl-1_1-x64.pdb
    openssl.exe
    openssl.pdb

Just flagging this in case there are other files that are not being created?

Thanks

Mike

**Comment by DDvO** [comment]
The difference you noticed is due to the configuration option `no-shared`, which in the first case prevents *.dll and *.pdb files to be produced for libcrypto and libssl, as these libs get statically linked.

**Comment by mikejhathaway** [comment]
Hi,

I did a fresh download this morning and tried the build process, nmake runs but ends with the following:

           "C:\Perl64\bin\perl.exe" "util\mkdef.pl" crypto 32 > libcrypto.def
            IF EXIST libcrypto-1_1-x64.dll.manifest DEL /F /Q libcrypto-1_1-x64.dll.manifest
            link /nologo /debug /dll  /nologo /debug  /implib:libcrypto.lib /out:libcrypto-1_1-x64.dll 
    /def:libcrypto.def @C:\Users\ADMINI~1\AppData\Local\Temp\nm7FDE.tmp || (DEL /Q libcrypto.* 
    libcrypto-1_1-x64.* && EXIT 1)
    libcrypto.def : error LNK2001: unresolved external symbol CMP_SRV_CTX_create
    libcrypto.def : error LNK2001: unresolved external symbol CMP_SRV_CTX_delete
    libcrypto.def : error LNK2001: unresolved external symbol CMP_SRV_CTX_get0_ctx
    libcrypto.def : error LNK2001: unresolved external symbol CMP_SRV_CTX_set1_caPubsOut
    libcrypto.def : error LNK2001: unresolved external symbol CMP_SRV_CTX_set1_certOut
    libcrypto.def : error LNK2001: unresolved external symbol CMP_SRV_CTX_set1_chainOut
    libcrypto.def : error LNK2001: unresolved external symbol CMP_SRV_CTX_set_accept_raverified
    libcrypto.def : error LNK2001: unresolved external symbol CMP_SRV_CTX_set_accept_unprotected
    libcrypto.def : error LNK2001: unresolved external symbol CMP_SRV_CTX_set_checkAfterTime
    libcrypto.def : error LNK2001: unresolved external symbol CMP_SRV_CTX_set_grant_implicit_confirm
    libcrypto.def : error LNK2001: unresolved external symbol CMP_SRV_CTX_set_pollCount
    libcrypto.def : error LNK2001: unresolved external symbol CMP_SRV_CTX_set_send_error
    libcrypto.def : error LNK2001: unresolved external symbol 
    CMP_SRV_CTX_set_send_unprotected_errors
    libcrypto.def : error LNK2001: unresolved external symbol CMP_SRV_CTX_set_statusInfo
    libcrypto.def : error LNK2001: unresolved external symbol CMP_mock_server_perform
    libcrypto.lib : fatal error LNK1120: 15 unresolved externals
    NMAKE : fatal error U1077: 'link' : return code '0x1'
    Stop.
    NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\nmake.exe"' : return code '0x2'
    Stop.

I also tried nmake test which fails with:

    Microsoft (R) Program Maintenance Utility Version 14.00.24210.0
    Copyright (C) Microsoft Corporation.  All rights reserved.

    makefile(15637) : fatal error U1033: syntax error : ':' unexpected
    Stop.
    NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\nmake.exe"' : return code '0x2'
    Stop.

And nmake install fails with:

    Microsoft (R) Program Maintenance Utility Version 14.00.24210.0
    Copyright (C) Microsoft Corporation.  All rights reserved.

    makefile(15637) : fatal error U1033: syntax error : ':' unexpected
    Stop.

Hope this helps?

Regards

Mike

**Comment by mikejhathaway** [comment]
Sorry, am a little lost should I be pulling from cmpossl or using 1.0.2 and the back port method?

**Comment by mpeylo** [comment]
Sorry for the confusion - I hope that my last commit fixes the issue with building cmpossl (without the need to backport). *Executing* the tests might break on Windows now - but you can ignore that for now.

**Comment by mpeylo** [comment]
Sorry for all this confusion, for Windows, I am a bit fishing in the dark here. My last changes to test/build.info is 1:1 in line with the comments in that file and also looks like other "examples" there.

What about using the "no-tests" config option? That should just skip the whole tests - which you not really need if you just want to use it.

**Comment by mikejhathaway** [comment]
So I used the steps from the wiki, and tied to compile vs some of the more advanced options available and the 'no-tests' option makes little difference:

    C:\work\cmpossl>"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat"

    C:\work\cmpossl>perl Configure VC-WIN32 no-tests
    Configuring OpenSSL version 1.1.1-pre3-dev (0x10101003L) for VC-WIN32
    Using os-specific seed configuration
    Creating configdata.pm
    Creating makefile

    **********************************************************************
    ***                                                                ***
    ***   If you want to report a building issue, please include the   ***
    ***   output from this command:                                    ***
    ***                                                                ***
    ***     perl configdata.pm --dump                                  ***
    ***                                                                ***
    **********************************************************************

    C:\work\cmpossl>nmake

    Microsoft (R) Program Maintenance Utility Version 14.00.24210.0
    Copyright (C) Microsoft Corporation.  All rights reserved.

            "C:\Perl64\bin\perl.exe" "-I." -Mconfigdata "util\dofile.pl"  "-omakefile" 
    "crypto\include\internal\bn_conf.h.in" > crypto\include\internal\bn_conf.h
            "C:\Perl64\bin\perl.exe" "-I." -Mconfigdata "util\dofile.pl"  "-omakefile" 
    "crypto\include\internal\dso_conf.h.in" > crypto\include\internal\dso_conf.h
            "C:\Perl64\bin\perl.exe" "-I." -Mconfigdata "util\dofile.pl"  "-omakefile" 
    "include\openssl\opensslconf.h.in" > include\openssl\opensslconf.h
            "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\nmake.exe" /                   depend 
    && "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\nmake.exe" /                   _all
    
    Microsoft (R) Program Maintenance Utility Version 14.00.24210.0
    Copyright (C) Microsoft Corporation.  All rights reserved.
    

    Microsoft (R) Program Maintenance Utility Version 14.00.24210.0
    Copyright (C) Microsoft Corporation.  All rights reserved.

    makefile(12936) : fatal error U1033: syntax error : ':' unexpected
    Stop.
    NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\nmake.exe"' : 
    return code '0x2'
    Stop.

**Comment by mpeylo** [comment]
Strange. However, I found a small thing I overlooked in tests/build.info. Just fixed that and committed it. Please test.

This might have also affected the makefile if tests are not actually built. The build scripting of OpenSSL is complicated, sorry for that.

If that doesn't work, could you send the "makefile" generated? The nmake output you quoted unfortunately doesn't show the offending line, but maybe it is anyway visible there what might cause the unexpected ':'.

**Comment by DDvO** [comment]
Hi Mike,

we currently have the problem that only I can test with the Windows VC setup and I'm on a business trip since yesterday afternoon until tomorrow and thus can do only superficial analysis right now.

What I already know is that the ":" error is due to some more general issue with the build machinery of OpenSSL for VC: some portions of some compiler error messages end up in the `makefile`.
This apparently is triggered by some other issue where I suspect that some OpenSSL meta file relevant for VC builds is not complete w.r.t. CMP.

So at the moment I can only ask for patience till (likely) end of the week...

Regards,
  David

**Comment by mikejhathaway** [comment]
Thanks Martin and David for all the helpful comments and assistance so far with this, sorry I too was busy with another project yesterday so I was not able to look at this until now and completely understand WRT work travel, we all have day jobs that take priority. 

I tried to pull a fresh copy and run the build process again this morning with the 'no-shared' option at the configure phase but still get the following when running nmake install:

    C:\work\cmpossl>nmake install

    Microsoft (R) Program Maintenance Utility Version 14.00.24210.0
    Copyright (C) Microsoft Corporation.  All rights reserved.

    makefile(15761) : fatal error U1033: syntax error : ':' unexpected
    Stop.

So something is still not right.

I have zipped and included the makefile to see if that can throw any light on what is wrong for when you get time to look at this.

[makefile.zip](https://github.com/mpeylo/cmpossl/files/1946009/makefile.zip)

Thanks again

Mike

**Comment by DDvO** [comment]
Hi Mike,

thanks for your understanding and also for your further feedback including the broken `makefile`.
When having a look at it at the given line (which is very long), you will see that it pertains to `apps\apps.obj` and contains some garbage near its end. Within the file dependency list some compiler warning output appears:
... `C:\work\cmpossl\include\openssl/x509v3err.h apps.c apps\apps.c(2106): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data apps\apps.c(2111): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data apps\apps.c(2332): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data c:\program files (x86)\windows kits\8.1\include\shared\poppack.h` ...

As I wrote yesterday, actually several things are/were broken in recent OpenSSL pre-1.1.1 versions regarding native Windows builds using VC. In particular, some compiler error/warning messages end up in the `makefile`. 

I think you get warnings for `apps/apps.c`, which are independent of our CMP extension and which I cannot reproduce, because you were trying to build 64-bit binaries, for which OpenSSL has some more problems. Better stick to VC-WIN32 for now. Yet also for this architecture I was able to reproduce some incompatibility specifically regarding `apps/cmp.c` on Monday and fix it.

VC is generally very picky when generating DLLs. I just spotted two shortcomings of the CMP-related API that showed up only for our CMP test code and fixed them. I also found out why the CMP tests failed when built with VC (namely, when reading DER-coded files, binary mode is strictly needed) and fixed this as well. 

Now both the shared and non-shared variants of VC-WIN32 and Cygwin builds as well as the (CMP-related) tests work for me. I am confident that they now also work for you. Before trying a new build, I suggest using `nmake distclean`, then`git pull` (on our standard branch, which is `cmp`), and then `perl Configure VC-WIN32` as usual.

Cheers,
  David

**Comment by mikejhathaway** [comment]
Hi David,

Many Thanks for the continued assistance!

I grabbed a fresh copy of the CMP branch this morning and ram nmake distclean before I start as you suggest and have switched to try to build a 32 bit version, unfortunately nmake test and nmake install still fail:

    C:\work\cmpossl>nmake test

    Microsoft (R) Program Maintenance Utility Version 14.00.24210.0
    Copyright (C) Microsoft Corporation.  All rights reserved.
    
            "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\nmake.exe" /                   depend 
    && "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\nmake.exe" /                   _tests

    Microsoft (R) Program Maintenance Utility Version 14.00.24210.0
    Copyright (C) Microsoft Corporation.  All rights reserved.
    
    
    Microsoft (R) Program Maintenance Utility Version 14.00.24210.0
    Copyright (C) Microsoft Corporation.  All rights reserved.
    
    NMAKE : fatal error U1073: don't know how to make 'C:\Program'
    Stop.
    NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\nmake.exe"' : 
    return code '0x2'
    Stop.

    C:\work\cmpossl>nmake install

    Microsoft (R) Program Maintenance Utility Version 14.00.24210.0
    Copyright (C) Microsoft Corporation.  All rights reserved.

            "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\nmake.exe" /                   depend 
    && "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\nmake.exe" /                   _all
    
    Microsoft (R) Program Maintenance Utility Version 14.00.24210.0
    Copyright (C) Microsoft Corporation.  All rights reserved.
    
    
    Microsoft (R) Program Maintenance Utility Version 14.00.24210.0
    Copyright (C) Microsoft Corporation.  All rights reserved.

    NMAKE : fatal error U1073: don't know how to make 'C:\Program'
    Stop.
    NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\nmake.exe"' : 
    return code '0x2'
    Stop. 

I get the same result for shared and non-shared configure settings.

Any ideas?

Regards

Mike

**Comment by DDvO** [comment]
Hi Mike,

this is yet another instance of the various recent general OPENSSL issues with VC builds that I've been referring to this week. In particular, I wrote last time but apparently was not clean enough:

> I also sometimes have the problem that nmake works at most one time and then the makefile gets garbled by the internal call to nmake depend when using nmake again. Workarounds are to re-configure the build and to use nmake _all and nmake _tests, respectively, which skip the broken nmake depend.

So, after the first run of nmake, one must not run it again in the normal way, but use the internal goal symbols. 

In order to get back to usable state, use "nmake distclean".

Then configure as usual,

Then call "nmake" as usual", but use this command only once!

For any further builds, tests, and install, use "nmake _all", "nmake _test", and "nmake _install",
which avoid the broken internal "nmake depend".

To avoid the need to re-build from scratch, you may keek a backup copy of the makefile and restore it whenever you accidentally used "nmake" in the normal way.

Regards,
  David

**Comment by mikejhathaway** [comment]
Hi David,

Many thanks for this, I have been successful in building the 32-bit version... 

Thanks very much for the help here!

Will close this off and try 64-bit in the future.

Regards

Mike
