### ISSUE TITLE
PKI enrollment signature verification failure - question

### ISSUE THREAD

**Issue by mikejhathaway** [mpeylo/cmpossl#133]
Hi There,

Am testing out the CMP client and am getting the following when using 3GPP vendor certificates for enrollment, what key usage is the CMP client looking for from a CA, Certificate Sign, CRL Sign are standard for a CA so am a little confused by the error?

    C:\work>openssl cmp -cmd ir -server 10.59.63.170:8040 -path cmpv2/CMPConfig1 -cert cmp_client.cer -key cmp_client.key -certout cmp_client_new.pem -newkey cmp_client_new.key -subject "/CN=cmp_client" -extracerts DeviceCA.cer -implicitconfirm -srvcert CMPCA.cer
    CMP INFO: using OpenSSL configuration file 'C:\tools\OpenSSL\SSL/openssl.cnf'
    warning: no [cmp section found in config file 'C:\tools\OpenSSL\SSL/openssl.cnf'; will thus use just 
    [default] and unnamed section if present
    CMP INFO: sending ir
    CMP INFO: got response
    CMP ERROR: 350AA0B0:CMP routines:CMP_verify_signature:wrong key 
    usage:crypto\cmp\cmp_vfy.c:50:
    CMP ERROR: 350A808E:CMP routines:CMP_validate_msg:invalid certificate:crypto\cmp\cmp_vfy.c:236:
    signature verification at depth=-1 error=1 (unspecified certificate verification error)
    failure for:
        certificate
            Subject: C=GB, O=ACME, OU=Certification Authorities, CN=CMP Test Certification Authority
            self-signed
            Serial Number: 1502804345 (0x5992f979)
            Validity
                Not Before: Aug 15 13:09:05 2017 GMT
                Not After : Aug 15 13:39:05 2027 GMT
            X509v3 extensions:
                X509v3 Private Key Usage Period:
                    Not Before: Aug 15 13:09:05 2017 GMT, Not After: Aug 15 13:39:05 2027 GMT
                X509v3 Key Usage:
                    Certificate Sign, CRL Sign
                X509v3 Authority Key Identifier:
                    keyid:33:56:09:C5:B8:A9:3B:B5:39:D3:9E:1C:E0:7E:D3:0C:CE:7A:66:26
    
                X509v3 Subject Key Identifier:
                    33:56:09:C5:B8:A9:3B:B5:39:D3:9E:1C:E0:7E:D3:0C:CE:7A:66:26
                X509v3 Basic Constraints:
                    CA:TRUE
    CMP ERROR: 3509B088:CMP routines:CMP_PKIMESSAGE_check_received:error validating 
    protection:crypto\cmp\cmp_lib.c:1809:

Thanks

Mike

**Comment by DDvO** [comment]
Hi Mike,

the typical problem here is that the CMP server uses for its signature-based protection of its CMP response message a certificate that does not allow the key usage "digitalSignature". On the other hand, this key usage is needed here because the server's certificate is used in this case not for cert/CRL signing, but for general (data) signing.
We've provided a simple workaround for such situations: the `-ignore_keyusage` option.

Cheers,
  David

**Comment by mikejhathaway** [comment]
Hi David,

Thanks, I added the key usage of digitalSignature to my CA as it is signing CMP messages with its private key but I still get the same output even if I use the -ignore_keyusage flag at the end of the command, now OpenSSL indicates that the cert is invalid which I suspect is due to the fact that I added digitalSignature to the CA Cert:

    C:\work>openssl cmp -cmd ir -server 10.59.63.170:8040 -path cmpv2/CMPConfig1 -cert 
    cmp_client_2.cer -key cmp_client_2.key -certout cmp_client_new_2.pem -newkey cmp_client_new_2.key -subject "/CN=cmp_client2" -extracerts DeviceCA_b64.cer -implicitconfirm -srvcert CMPCA_updated_2_b64.cer -ignore_keyusage
    CMP INFO: using OpenSSL configuration file 'C:\tools\OpenSSL\SSL/openssl.cnf'
    warning: no [cmp section found in config file 'C:\tools\OpenSSL\SSL/openssl.cnf'; will thus use just 
    [default] and unnamed section if present
    CMP INFO: sending ir
    CMP INFO: got response
    CMP INFO: sending certConf
    CMP INFO: got response
    CMP ERROR: 04091068:rsa routines:int_rsa_verify:bad signature:crypto\rsa\rsa_sign.c:220:
    CMP ERROR: 350AA088:CMP routines:CMP_verify_signature:error validating protection:crypto\cmp\cmp_vfy.c:93:
    CMP ERROR: 350A808E:CMP routines:CMP_validate_msg:invalid certificate:crypto\cmp\cmp_vfy.c:236:
    signature verification at depth=-1 error=1 (unspecified certificate verification error)
    failure for:
        certificate
            Subject: C=GB, O=ACME, OU=Certification Authorities, CN=CMP Test Certification Authority
            self-signed
            Serial Number: 1502805741 (0x5992feed)
            Validity
                Not Before: Apr 30 14:55:36 2018 GMT
                Not After : Apr 30 15:25:36 2028 GMT
            X509v3 extensions:
                X509v3 Basic Constraints: critical
                    CA:TRUE
                X509v3 Key Usage: critical
                    Digital Signature, Certificate Sign, CRL Sign
                X509v3 Private Key Usage Period:
                    Not Before: Apr 30 14:55:36 2018 GMT, Not After: Apr 30 15:25:36 2028 GMT
                X509v3 Authority Key Identifier:
                    keyid:FF:63:BC:8F:6E:9C:B6:89:52:54:7C:D8:3C:E3:E1:34:BC:C0:54:82
    
                X509v3 Subject Key Identifier:
                    FF:63:BC:8F:6E:9C:B6:89:52:54:7C:D8:3C:E3:E1:34:BC:C0:54:82
    CMP ERROR: 3509B088:CMP routines:CMP_PKIMESSAGE_check_received:error validating protection:crypto\cmp\cmp_lib.c:1809:

Regards

Mike

**Comment by mikejhathaway** [comment]
Hi David,

Thanks, I created a new debug build but when I enroll only rsp1.der is produced, any thoughts on why this might be the case, also I dont seem to be able to dump the contents using OpenSSL, how can I read/validate the contents?

Thanks

Mike

**Comment by DDvO** [comment]
Hi Mike, when you do not use `-disableconfirm` as I suggested as workaround but `-implicitconfirm` as you did before and the implicit confirmation is not granted by the server, then you should see not only 
```
CMP INFO: sending ir
CMP INFO: got response
```
but also
```
CMP INFO: sending certConf
CMP INFO: got response
```
as you quoted above, and both `rsp1.der` and `rsp2.der` should be produced.

In any case, you can use, e.g., `openssl asn1parse -inform der -in rsp1.der`
or [dumpasn1](https://github.com/clibs/dumpasn1) or some online ASN.1 viewer to dump the contents of CMP messages in more or less readable form (while all these are not CMP-specific).

Of course, a signature value cannot be checked manually.
Maybe only the signature of pkiConf goes wrong, so I suggest trying out also other types of requests/responses such as cr/cp and rr/rp.

**Comment by mpeylo** [comment]
Hi,

Wireshark traces would be the easiest way to see what happens. 

You seem to use an external entity certificate following RFC 4210 E.7 - I speculate that the CA is switching to a different certificate to sign certConf, and the client doesn't trust that (yet)

Cheers,
Martin

**Comment by DDvO** [comment]
A non-trusted signer certificate would lead to a different error message. The quoted message
```
04091068:rsa routines:int_rsa_verify:bad signature:crypto\rsa\rsa_sign.c:220:
```
indicates a low-level signature verification error where the signature value does not match.

**Comment by mpeylo** [comment]
A Wireshark trace might help to quickly identify the root cause of the issue - unless the server implementation would have a really deep problem when generating the signature.

**Comment by DDvO** [comment]
Are the signing certs, as they should be contained in the extraCerts at the end of `rsp1.der` and `rsp2.der`, the same?
If not, you need to make sure that both these certs get trusted, for instance by using the `-trusted` option to provide their root CA cert(s).

**Comment by mikejhathaway** [comment]
I am looking into an issue with WireShark as it is not capturing the IR message, I do see the CA returning a status=accepted message, unfortunately I cannot share the capture as it has some sensitive information in it. 

The CA has the option to either sign CMP messages with its private key or a protocol signing key, in either case I get the signature validation issues with the "Wrong Key Usage" and "invalid certificate" messages. I am wondering if my enrollment command is correct, the example I am using is from EJBCA so may not be correct with the current version of OpenSSL CMP?

**Comment by DDvO** [comment]
EJBCA itself certainly produces technically valid signature values. Yet it potentially uses different certs for the ip and certConf messages, which I consider a bug.

Again, do the certs in the `extraCerts` field at the end of the responses match the cert(s) you provide as argument of the `-srvcert` or `-trusted` options? You need to compare their subject/issuer (and subjectKeyIdentifier/issuerKeyIdentifier fields if present).

**Comment by mikejhathaway** [comment]
I can see the extraCerts message coming back with 2 certs in it, the serial number, DB etc on one of these matches the cert I am using with -srvcert

**Comment by DDvO** [comment]
This is a further indication that the signature verification failure is due to some more low-level mismatch.

**Comment by mikejhathaway** [comment]
Yes, I am looking at this now, I have a copy of this VM running in another environment and I am getting a different result, my main concern here was the command/config I am running to execute the test.

Will come back to you soon.

Thanks

**Comment by DDvO** [comment]
Good morning, 

as mentioned Martin and I suspect that the CA uses different certs when signing its `ip` and `pkiConf` messages. If so, as written earlier, you cannot use `srvcert` but must use `trusted` (with the common root cert of both signing certs or the two different root certs of them, depending on your CA setup).

Could you please verify that the extraCerts match your `srvcert `option for both types of responses. In particular, does the first extraCert in both responses have the following field values?

```
        Subject: C=GB, O=ACME, OU=Certification Authorities, CN=CMP Test Certification Authority

            X509v3 Subject Key Identifier:
                FF:63:BC:8F:6E:9C:B6:89:52:54:7C:D8:3C:E3:E1:34:BC:C0:54:82
```
If so, you should be able to stick with `srvcert` referring to this CA cert, else, you need to switch to `trusted`.

**Comment by DDvO** [comment]
Hi again Mike, I meanwhile have a very concrete suspicion:
Since you recently updated your CA cert to correct its key usage while you kept the subject of the cert, it could well be that in some place(s) still the old cert is used, leading to a pretty subtle key mismatch.

**Comment by mikejhathaway** [comment]
Hi David and Martin,

Once again thanks for all the great help, I have been making progress with learning about the CMP client and also the different behaviors of different vendors implementations of both the CMP server side and the client side, I am traveling on business right now but I can say that having reverted to a snapshot (before updating my CA keys) and using `-ignore_keyusage` I am able to see the CMP enrollment now progressing, there is an issue at my CA I need to look into and I will be able to get to that at the end of this week, I hope.

Stay tuned and thanks again!

Regards

Mike

**Comment by mikejhathaway** [comment]
Hi David and Martin,

Sorry for not replying sooner, I've been traveling again.

Seems my CA needed an update and was the cause of the invalid signature, I now have ir and kur working successfully, thank you for the help with getting the client working and all the guidance. I have a couple of other questions that are related to configuring the client but will create a separate post for these.

I also found that the environment I am testing in not all CA's sign CMP messages with the protocol signing cert and when they don't they don't all have the digitalSignature bit set in the CA key usage, seems that not everyone sticks rigidly to the 3GPP specifications, I have also found that the majority of clients seem happy in processing certs that have been signed by a key\cert that is missing the digitalSignature bit?!? 

Thanks again

Mike

**Comment by DDvO** [comment]
Hi Mike,

you are welcome. Thanks also for your feedback; no problem that it took some time.

The cert version mismatch you apparently had could have been spotted easily if the CA uses the (optional) senderKID field in the header of messages it signs and if this field is checked by the client. We recently enhanced CMPforOpenSSL to do so also when the `srvcert` option is used to pin the cert used for verifying message protection.

The key usage bit 'digitalSignature' is indeed required by the 3GPP CMP profile. It is defined, in conjunction with other potential key usage bits, in [RFC 5280](https://tools.ietf.org/html/rfc5280#section-4.2.1.3). Yet many certificates issuer do not take sufficient care to set appropriate key usage extensions and (possibly in consequence of this) most implementations verifying certificates (including OpenSSL's TLS implementation) are very lax/permissive regarding the restrictions implied by the key usage extensions.

Regards,
  David

**Comment by mikejhathaway** [comment]
Hi David,

The issue was not due to the CA signing with the wrong key it was a fault where internally the pkiConf Header was being changed, the CA rectifies this and the result is enrollment is now working.

One thing I have noted while testing is that the CMP client doesn’t seem to understand CMP messages that are signed by a protocol signing key, in this instance the CA is creating a key\cert used to sign CMP messages, the cert is signed by the CA and has the correct key usage as per 3GPP however the CMP client doesn’t see this as trusted and doesn’t seem able to chain it to the CA cert supplied in the srvcert option.

For now this is not an issue as you can use the CA key with the ignorekeyusage setting.

Regards

Mike

**Comment by DDvO** [comment]
Hi Mike,

it looked like the client was configured with an unsuitable srvcert, such as the old version before you added the digitalSignature key usage. Interesting that specifically the `pkiConf` header was somehow wrong, but this alone does not explain the mismatch of the actual CA's protocol (message protection) key and `srvcert`.

Your second remark indicates that you misunderstood the semantics of the `srvcert` option. This is not meant to refer to the CA's issuing key but directly to the CA's CMP protocol signing key. Maybe the documentation does not clearly enough state that using `srvcert` no chain of certs is used?
The `-help` output of the `cmp` command says:
`Specific CMP server cert to use and trust directly when verifying responses`
The `cmp` man page says:
> `<-srvcert filename>`
> `The specific CMP server certificate to use and trust directly
> for verifying the protection of response messages.
> May be set alternatively to the B<-trusted> option
> if the certificate is available and should be directly trusted.`

The situation is complicated by the fact that at least in some configurations of EJBCA it signs the `ip`/`cp`/`kup` with its issuing key and the `pkiConf` with some other (protocol) key. In such situations, one cannot use the `srvcert` option but must resort to the more flexible `trusted` option. Have you tried this?

Regards,
  David

**Comment by mikejhathaway** [comment]
Hi David,

Thanks. I think I mentioned in this post earlier that the example I started with rightly or wrongly was from EJBCA and with hindsight probably not a good idea.

Essentially I would like to be able to emulate eNodeB enrollment and shared secret enrollment, I am focusing on the eNodeB part first and was going to open a new post to ask questions on how best to structure a configuration where I am not specifying the srvcert but instead specify the CA name instead, I’ve seen the options in the help but have not had a free moment to begin any testing.

Regards

Mike

**Comment by mikejhathaway** [comment]
Thanks David,

It is a self-signed CA so will switch to the Trusted option and give this a try. I did try the ‘-recipient’ option as I just wanted to specify the DN of theCA but this seems to only work in conjunction with ‘-trusted’ or ‘-svrcert’

Regards

Mike
