### ISSUE TITLE
Convert PKCS#10 CSR to raVerified CRMF certRequest

### ISSUE THREAD

**Issue by mpeylo** [mpeylo/cmpossl#151]
Effective use case for many RAs will be to receive PKCS#10 from legacy EEs and obtain a certificate for it from a CA. 

There could be a function in CRMF that takes a PKCS#10 and converts it to an "raVerified" CRMF certRequest.

A new option in the cmp application could then trigger creating e.g. an IR/KUR based on that certRequest generated out oft the PKCS#10.

There would be benefits of using certRequest over the p10cr:
- missing CMP server-side support for p10cr
- opportunity for the RA to enforce fields in the certTemplate (pending RA-specific features for this)
- have multiple certRequests derived from multiple PKCS#10s sent in one CMP message (pending availability of the general multiple-requests feature)

**Comment by DDvO** [comment]
This is meanwhile [implemented](https://github.com/openssl/openssl/pull/13841) as part of the upcoming OpenSSL version 3.0.
