### ISSUE TITLE
not ignoring HTTP Content-Type header of answer

### ISSUE THREAD

**Issue by mpeylo** [mpeylo/cmpossl#152]
The HTTP Content-Type header this is currently silently ignored. 

In case that is not set, there should likely be at least a warning.

In case the HTTP Content-Type is set to anything else than application/pkixcmp, a relevant error should be triggered.

**Comment by DDvO** [comment]
I've developed an enhanced HTTP client for OpenSSL, which is currently a pull request there: https://github.com/openssl/openssl/pull/10667. Among others, this includes the check requested above.
Hope this will be integrated with the OpenSSL master soon, and then our CMP contribution will benefit from this enhancement.

**Comment by DDvO** [comment]
The improvement meanwhile has become part of OpenSSL and of our `cmp-dev` master branch.
