### ISSUE TITLE
Plan to merge cmpossl to openssl master  

### ISSUE THREAD

**Issue by shishirpandey29** [mpeylo/cmpossl#155]
Hello ,

Is there any plan to merge cmpossl changes in openssl master branch.

Regards
Shishir

**Comment by DDvO** [comment]
Yes, this is already in work for some time. You can see the current state of affairs at https://github.com/openssl/openssl/pull/7646.
Cheers, David

**Comment by shishirpandey29** [comment]
ok, thanks you
