### ISSUE TITLE
CMP_PKIFAILUREINFO_MAX bit pattern does not fit in type int

### ISSUE THREAD

**Issue by mickae1** [mpeylo/cmpossl#156]
Hi, when i tried to compile, I've this error 

`crypto/cmp/cmp_int.h:280:3: error: #error CMP_PKIFAILUREINFO_MAX bit pattern does not fit in type int
 # error  CMP_PKIFAILUREINFO_MAX bit pattern does not fit in type int
   ^
In file included from ././include_cmp/openssl/crmf.h:42:0,
                 from <command-line>:0:
crypto/cmp/cmp_int.h: In function 'sk_OSSL_CMP_REVDETAILS_delete_ptr':
./include_cmp/openssl/safestack_backport.h:97:44: warning: passing argument 2 of 'sk_delete_ptr' discards 'const' qualifier from pointer target type
                                            (const void *)ptr); \`

**Comment by DDvO** [comment]
Interesting to see this precaution check fail in practice. The above error is shown in the following case:
```
#define OSSL_CMP_PKIFAILUREINFO_MAX 26
#define OSSL_CMP_PKIFAILUREINFO_MAX_BIT_PATTERN \
    ( (1<<(OSSL_CMP_PKIFAILUREINFO_MAX+1)) - 1)
#if OSSL_CMP_PKIFAILUREINFO_MAX_BIT_PATTERN > INT_MAX
```
so `INT_MAX` is wrongly defined in your header files or sizeof(int) is < 4 in your target architecture or the calculation of `OSSL_CMP_PKIFAILUREINFO_MAX_BIT_PATTERN` goes wrong in your compiler. Can you check these three values?

**Comment by DDvO** [comment]
So your `sizeof(int)` is 4 and thus is fine, and thus the error should be a false positive.

I suggest you compile the following and report its outcome.
```
#define OSSL_CMP_PKIFAILUREINFO_MAX 26
#define OSSL_CMP_PKIFAILUREINFO_MAX_BIT_PATTERN \
    ( (1<<(OSSL_CMP_PKIFAILUREINFO_MAX+1)) - 1)

   printf("INT_MAX=%d, OSSL_CMP_PKIFAILUREINFO_MAX_BIT_PATTERN=%x\n,
             INT_MAX,         OSSL_CMP_PKIFAILUREINFO_MAX_BIT_PATTERN)
```

**Comment by DDvO** [comment]
Since the value of `INT_MAX` is fine, the preprocessor of your compiler must get the value of the expression  `((1<<(26+1)) - 1)` or the comparison `OSSL_CMP_PKIFAILUREINFO_MAX_BIT_PATTERN > INT_MAX` wrong. Will be interesting to set what its result is.

**Comment by mickae1** [comment]
Hi,

I've tested:

   printf("test1 %d\n", ( (1<<(OSSL_CMP_PKIFAILUREINFO_MAX+1)) - 1)    );
   printf("test2 %d\n", (1<<(OSSL_CMP_PKIFAILUREINFO_MAX+1))    );
   printf("test3 %d\n", 1<<(OSSL_CMP_PKIFAILUREINFO_MAX+1)    );
   printf("test4 %d\n", (OSSL_CMP_PKIFAILUREINFO_MAX+1) );

the result;

test1 134217727
test2 134217728
test3 134217728
test4 27

**Comment by mickae1** [comment]
It is normal that 1 << 27 gives :  134217728

**Comment by mickae1** [comment]
and the result of your questions: 
INT_MAX=7fffffff, OSSL_CMP_PKIFAILUREINFO_MAX_BIT_PATTERN=7ffffff, OSSL_CMP_PKIFAILUREINFO_MAX_BIT_PATTERN > INT_MAX=0


I don't understand how your test could pass before .....

**Comment by DDvO** [comment]
So your compiler did the calculations right.
I don't understand why you apparently got the error "CMP_PKIFAILUREINFO_MAX bit pattern does not fit in type int", since `OSSL_CMP_PKIFAILUREINFO_MAX_BIT_PATTERN =< INT_MAX` holds.

**Comment by mickae1** [comment]
because it is < and not <= !

#define OSSL_CMP_PKIFAILUREINFO_MAX_BIT_PATTERN \
    ( (1<<(OSSL_CMP_PKIFAILUREINFO_MAX+1)) - 1)
#if OSSL_CMP_PKIFAILUREINFO_MAX_BIT_PATTERN > INT_MAX

**Comment by DDvO** [comment]
No, note that the printed value of OSSL_CMP_PKIFAILUREINFO_MAX_BIT_PATTERN has one 'f' less than INT_MAX and thus is much smaller (which was expected), and the error occurs if it is larger, so no error if it is less or equal.

**Comment by mickae1** [comment]
i just checked the compiler error one more time : 

**crypto/cmp/cmp_int.h:279:47: warning: "INT_MAX" is not defined [-Wundef]**
 #if OSSL_CMP_PKIFAILUREINFO_MAX_BIT_PATTERN > INT_MAX

the problem is that INT_MAX is not defined

**Comment by DDvO** [comment]
Then something must be wrong regarding the header file `limits.h`, which should define `INT_MAX`.
`cmp_int.h` includes `ossl_typ.h`, which should includes `limits.h`.
I just found that this is the case only since OpenSSL 1.1.0-pre2.

Which version of OpenSSL are you compiling with?
If it is anything before (in particular, any 1.0.2*), I suggest as a workaround adding `#include <limits.h>` or using the gcc command-line argument `-include limits.h`.

Moreover, for compiling the CMP lib with OpenSSL 1.0.2 you will likely also need to add the following quirks to `CFLAGS`: `-Wno-discarded-qualifiers -Wno-incompatible-pointer-types -Wno-unused-parameter` as meanwhile described in the [Quick Start Guide](../wiki/Quick-Start).

**Comment by mickae1** [comment]
I'm not using openssl 1.0.2.

I'm using : OpenSSL 1.1.0f  25 May 2017

**Comment by DDvO** [comment]
Then I do not understand why `MAX_INT` is not defined in your case.
How far do you get when you manually add `limits.h` as I suggested above?

**Comment by DDvO** [comment]
@mickae1, does this work for you now?

**Comment by DDvO** [comment]
Closing this due to missing response. 
Works for me.
