### ISSUE TITLE
OSSL_CMP_puts() CMP_log_fd() issues

### ISSUE THREAD

**Issue by mpeylo** [mpeylo/cmpossl#164]
In e.g. commit d616bb6611a4e3ddeb6dabb563813b384c429ee5

OSSL_CMP_puts() does not return anything in case OPENSSL_NO_STDIO is defined, documentation does not mention how OPENSSL_NO_STDIO affects the function.

In CMP_log_fd():
- _len_ gets assigned, but not used afterwards (line 1366)
- it is (cannot be) not checked whether _msg_ function parameter is 0-terminated before strlen is used on it (line1367) and documentation appears not to mention that 0-termination would be required

**Comment by DDvO** [comment]
After recent changes to the log facility, this issue has disappeared for our  `cmp-dev´ branch.
Nevertheless I've just fixed it for `cmp`.

Note that, as usual, we implicitly assume that strings of type `char *` are NUL-terminated.
