### ISSUE TITLE
file cmp.cnf is missing

### ISSUE THREAD

**Issue by h-rueda** [mpeylo/cmpossl#180]
the page https://github.com/mpeylo/cmpossl/wiki/Quick-Start gives some typical use cases.

For those examples to work, we must initialize the OPENSSL_CONF variable with the command
`export OPENSSL_CONF=cmp.cnf`

However, the installer doesn't provide any cmp.cnf file at all.

The cmp.cnf file is missing after installation.

**Comment by mpeylo** [comment]
The content of the OpenSSL configuration file (e.g. cmp.cnf) is very specific to your CMP sever configuration, therefore it wouldn't make much sense to supply an example file. You will find an explanation with example in the **doc/man1/cmp.pod** file, which is in Plain Old Documentation format (pretty much human readable, e.g. VIM also has does excellent syntax highlighting). Depending on your make configuration, this file might be converted into Manual (.man) format during built - but it is likely quickest for you to red the POD file directly.

Easiest for you will be to open that file with an editor, and search for the "**Using a configuration file**" section.

I've added reference to that to the Quick-Start wiki
