### ISSUE TITLE
Error ip not received

### ISSUE THREAD

**Issue by Shriyanshmit** [mpeylo/cmpossl#185]
I am getting below message. Please help

root@ubuntu:/opt/openssl/bin# ./openssl cmp -cmd ir -server 132.186.189.206:444 -path api/cmp -config "" -secret pass:test -ref test -newkey Key-2019.pem -certout Key-2019.pem
OpenSSL:setup_ctx():apps/cmp.c:3216: WARNING: missing -recipient, -srvcert, -issuer, -oldcert or -cert; recipient will be set to "NULL-DN"
OpenSSL:send_receive_check():crypto/cmp/cmp_ses.c:183: INFO: sending ir
140641880569600:error:390B10A8:CMP routines:OSSL_CMP_MSG_http_perform:read timeout:crypto/cmp/cmp_http.c:516:
140641880569600:error:390A1098:CMP routines:OSSL_CMP_exec_IR_ses:ip not received:crypto/cmp/cmp_ses.c:199:

**Comment by DDvO** [comment]
As I wrote for the original issue #181 you opened, you have to check your connection.
You may use Wireshark to see if your request actually was sent.  If so and no response arrived then something is wrong but it's not a fault of the CMP client.
