### ISSUE TITLE
How can I use cmpforopenssl to apply for multiple certificates in batches?

### ISSUE THREAD

**Issue by gezhouyu** [mpeylo/cmpossl#186]
Hi Sir,
  
I want to know if the cmpforopenssl tool can send certificate request messages to the CA in batches, or can apply for multiple certificates at the same time in a message. How can I do it?

Best Regards,
Iya Ge

**Comment by DDvO** [comment]
Unfortunately this is not supported. 
See also the old feature request #67 which I have just generalized.
