### ISSUE TITLE
Hello, sir. When the cmp client applies for a certificate from the CA, can the parameters of the certificate template be added?

### ISSUE THREAD

**Issue by gezhouyu** [mpeylo/cmpossl#197]
Hello, sir.
When the cmp client applies for a certificate from the CA, can the parameters of the certificate template be added?

**Comment by DDvO** [comment]
All important fields can be set, of course. Check the documentation of the CLI and/or API.

**Comment by gezhouyu** [comment]
> All important fields can be set, of course. Check the documentation of the CLI and/or API.

Hi Sir,
I actually can not find which parameter can be used to configure the certificate template, can you give some tips, thank you so much.

Best wishes

**Comment by DDvO** [comment]
You can use at CLI level:
[-newkey filename] 
[-subject name] 
[-days number] 
[-reqexts name] 
[-sans spec] 
[-policies names]

**Comment by gezhouyu** [comment]
Hello, sir.
Can I provide instructions on how to apply for, update, and revoke certificates? After you know the meaning of the parameter, you still do not know how to use it. What is the correct command?

**Comment by DDvO** [comment]
Again, just read the documentation.
