### ISSUE TITLE
Does cmp for openssl support pollReq and certConf message types?

### ISSUE THREAD

**Issue by gezhouyu** [mpeylo/cmpossl#203]
Hi Sir,

I want to know if the cmpforopenssl tool can send pollReq and certConf message types?

Best Regards,
Iya Ge

**Comment by DDvO** [comment]
Dear Iya,

yes, it can. 

This could be more explicit from, e.g., the CLI documenation: https://github.com/mpeylo/cmpossl/blob/cmp/doc/man1/cmp.pod

I've just add the list of supported message types to https://github.com/mpeylo/cmpossl/wiki

Best regards,
  David
