### ISSUE TITLE
Can I set the validity period of a certificate when you use kur for a certificate update

### ISSUE THREAD

**Issue by gezhouyu** [mpeylo/cmpossl#204]
Hi sir,
  Can I set the validity period of a certificate when you use kur for a certificate update(such as the effective date and expiration date) ? Which parameter I can use?

Best wishes,
Iya

**Comment by Akretsch** [comment]
Normally the CA determines the validity.

**Comment by DDvO** [comment]
There is the `-days` option to specify the requested validity time of the new certificate in number of days.
