### ISSUE TITLE
cmpossl-cmp-lib5 OPENSSL_DIR=/usr/local make -f Makefile_cmp error build

### ISSUE THREAD

**Issue by mickae1** [mpeylo/cmpossl#209]
crypto/crmf/crmf_pbm.c:133:5: error: unknown type name 'EVP_MAC_CTX'
     EVP_MAC_CTX *mctx = NULL;
     ^

`root@MICKA:/Distrib/project/cmpossl/cmpossl-cmp-lib5# clear
root@MICKA:/Distrib/project/cmpossl/cmpossl-cmp-lib5# OPENSSL_DIR=/usr/local make -f Makefile_cmp
detected OpenSSL version 1.1.x
gcc -g -fPIC -I./include_cmp -DDEBUG_UNUSED -DPEDANTIC -pedantic -Wall -Wextra -Wswitch -Wsign-compare -Wmissing-prototypes -Wstrict-prototypes -Wshadow -Wformat -Wtype-limits -Wundef -D'DEPRECATEDIN_1_2_0(f)= '  -isystem /usr/local/include  -include ./include_cmp/openssl/crmf.h  crypto/crmf/crmf_asn.c crypto/crmf/crmf_err.c crypto/crmf/crmf_lib.c crypto/crmf/crmf_pbm.c crypto/cmp/cmp_asn.c crypto/cmp/cmp_ctx.c crypto/cmp/cmp_err.c crypto/cmp/cmp_http.c crypto/cmp/cmp_lib.c crypto/cmp/cmp_msg.c crypto/cmp/cmp_ses.c crypto/cmp/cmp_srv.c crypto/cmp/cmp_vfy.c -L/usr/local/lib -L/usr/local -Wl,-rpath=/usr/local/lib -Wl,-rpath=/usr/local -lcrypto -shared -o libcmp.so
crypto/crmf/crmf_pbm.c: In function 'OSSL_CRMF_pbm_new':
crypto/crmf/crmf_pbm.c:133:5: error: unknown type name 'EVP_MAC_CTX'
     EVP_MAC_CTX *mctx = NULL;
     ^
crypto/crmf/crmf_pbm.c:201:5: warning: implicit declaration of function 'EVP_MAC_CTX_new' [-Wimplicit-function-declaration]
     if ((mctx = EVP_MAC_CTX_new(EVP_get_macbyname("HMAC"))) == NULL
     ^
crypto/crmf/crmf_pbm.c:201:5: warning: implicit declaration of function 'EVP_get_macbyname' [-Wimplicit-function-declaration]
crypto/crmf/crmf_pbm.c:201:15: warning: assignment makes pointer from integer without a cast
     if ((mctx = EVP_MAC_CTX_new(EVP_get_macbyname("HMAC"))) == NULL
               ^
crypto/crmf/crmf_pbm.c:202:9: warning: implicit declaration of function 'EVP_MAC_ctrl' [-Wimplicit-function-declaration]
         || EVP_MAC_ctrl(mctx, EVP_MAC_CTRL_SET_MD, m) <= 0
         ^
crypto/crmf/crmf_pbm.c:202:31: error: 'EVP_MAC_CTRL_SET_MD' undeclared (first use in this function)
         || EVP_MAC_ctrl(mctx, EVP_MAC_CTRL_SET_MD, m) <= 0
                               ^
crypto/crmf/crmf_pbm.c:202:31: note: each undeclared identifier is reported only once for each function it appears in
crypto/crmf/crmf_pbm.c:203:31: error: 'EVP_MAC_CTRL_SET_KEY' undeclared (first use in this function)
         || EVP_MAC_ctrl(mctx, EVP_MAC_CTRL_SET_KEY, basekey, bklen) <= 0
                               ^
crypto/crmf/crmf_pbm.c:204:9: warning: implicit declaration of function 'EVP_MAC_init' [-Wimplicit-function-declaration]
         || !EVP_MAC_init(mctx)
         ^
crypto/crmf/crmf_pbm.c:205:9: warning: implicit declaration of function 'EVP_MAC_update' [-Wimplicit-function-declaration]
         || !EVP_MAC_update(mctx, msg, msglen)
         ^
crypto/crmf/crmf_pbm.c:206:9: warning: implicit declaration of function 'EVP_MAC_final' [-Wimplicit-function-declaration]
         || !EVP_MAC_final(mctx, mac_res, maclen))
         ^
crypto/crmf/crmf_pbm.c:214:5: warning: implicit declaration of function 'EVP_MAC_CTX_free' [-Wimplicit-function-declaration]
     EVP_MAC_CTX_free(mctx);
     ^
Makefile_cmp:94: recipe for target 'libcmp.so' failed
make: *** [libcmp.so] Error 1
root@MICKA:/Distrib/project/cmpossl/cmpossl-cmp-lib5#
`

**Comment by mpeylo** [comment]
You might want to provide more background on what code (branch / commit) you want to build on what system...

Also, what options did you use for config and what is Makefile_cmp?

**Comment by mickae1** [comment]
it works with cmpossl-cmp-lib4
