### ISSUE TITLE
While executing the command in jmeter, the response visible as

### ISSUE THREAD

**Issue by sonalijft** [mpeylo/cmpossl#211]

**Comment by sonalijft** [comment]
CMP INFO: using OpenSSL configuration file '/usr/local/ssl/openssl.cnf'
CMP INFO: no [cmp] section found in config file '/usr/local/ssl/openssl.cnf'; will thus use just [default] and unnamed section if present

**Comment by DDvO** [comment]
What is your problem? The diagnostics is correct and contains the warning that in the used config file there is no [cmp] section, which typically is a configuration error.

**Comment by sonalijft** [comment]
I am running the script on GUI mode using SSH command where the execute command
But in response  I am getting:----
CMP INFO: using OpenSSL configuration file '/usr/local/ssl/openssl.cnf'
CMP INFO: no [cmp] section found in config file '/usr/local/ssl/openssl.cnf'; will thus use just [default] and unnamed section if present

Which were not expected

The expected result is, this related result i am getting while executing in command prompt execute in NON GUI mode :- 
CMP INFO: using OpenSSL configuration file '/usr/local/ssl/openssl.cnf'
CMP INFO: no [cmp] section found in config file '/usr/local/ssl/openssl.cnf'; will thus use just [default] and unnamed section if present
CMP INFO: sending ir
CMP INFO: got response
CMP INFO: received 1 enrolled certificate, saving to file '/tmp/cert.crt'

So how I can resolve the issue in GUI mode

**Comment by DDvO** [comment]
I don't know JMeter and it's unclear what you mean by "GUI mode".
It looks like that in this case the CMP client gets stuck before sending the first request.
I have the suspicion that this happens while reading its input files.
You can try using a debugger or strace to find out the actual reason.

**Comment by DDvO** [comment]
@sonalijft, did you meanwhile find out why your CMP client call got stuck?

Most likely this is because it tries getting a password for reading an encrypted key file
or tries reading a key or certificate from STDIN while your GUI does not handle this.

**Comment by DDvO** [comment]
Closing this PR due to missing further input.
