### ISSUE TITLE
expected ')' before string constant in cmp_util.h during MAKE

### ISSUE THREAD

**Issue by oregano87** [mpeylo/cmpossl#219]
Hi
I tried to compile and install cmpossl but during calling MAKE the following error prompted
```
include/openssl/cmp_util.h:33:43: error: expected ')' before string constant
   33 | #  define OSSL_CMP_LOG_START OPENSSL_FUNC ":" OPENSSL_FILE ":" \
      |                                           ^~~
```

Output files attached
[config_output.txt](https://github.com/mpeylo/cmpossl/files/6036348/config_output.txt)
[make_output.txt](https://github.com/mpeylo/cmpossl/files/6036349/make_output.txt)
[perl_output.txt](https://github.com/mpeylo/cmpossl/files/6036350/perl_output.txt)

**Comment by DDvO** [comment]
This looks like a compiler incompatibility.
Yet meanwhile the `define OSSL_CMP_LOG_START` has been removed anyway.
Is the build problem now solved for you?

**Comment by oregano87** [comment]
Issue solved
