### ISSUE TITLE
don`t find the cmp-lib4

### ISSUE THREAD

**Issue by 1042198949** [mpeylo/cmpossl#244]
The remote is fine, so the issue must be elsewhere. 
As a workaround, please do in the `cmpossl` dir:
```
git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
git fetch 
git checkout cmp-lib4
```

_Originally posted by @DDvO in https://github.com/mpeylo/cmpossl/issues/221#issuecomment-948725567_
            

hello DDvO,
i don`t find the cmp-lib4

[pp@/tmp/gencmpclient/cmpossl]$ git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
[pp@/tmp/gencmpclient/cmpossl]$ git fetch
[pp@/tmp/gencmpclient/cmpossl]$ git checkout cmp-lib4
error: pathspec 'cmp-lib4' did not match any file(s) known to git.
[pp@/tmp/gencmpclient/cmpossl]$ git branch -r | grep cmp
  origin/cmp-ckg
  origin/cmp-ckg-before-2022-09-12
[pp@/tmp/gencmpclient/cmpossl]$

**Comment by 1042198949** [comment]
when i use cmake . ,  an error is reported

[pp@/tmp/gencmpclient]$ cmake .
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- generic CMP client version 2.0
-- using OpenSSL package, with version 1.0.2k
-- using OpenSSL hdrs from /usr/include
-- using OpenSSL libraries /usr/lib64/libcrypto.so, /usr/lib64/libssl.so
-- using libcmp
-- build mode: Release
-- Found Git: /usr/bin/git (found version "1.8.3.1")
-- fetching git submodule libsecutils
usage: git submodule [--quiet] add [-b <branch>] [-f|--force] [--name <name>] [--reference <repository>] [--] <repository> [<path>]
   or: git submodule [--quiet] status [--cached] [--recursive] [--] [<path>...]
   or: git submodule [--quiet] init [--] [<path>...]
   or: git submodule [--quiet] deinit [-f|--force] [--] <path>...
   or: git submodule [--quiet] update [--init] [--remote] [-N|--no-fetch] [-f|--force] [--rebase] [--reference <repository>] [--merge] [--recursive] [--] [<path>...]
   or: git submodule [--quiet] summary [--cached|--files] [--summary-limit <n>] [commit] [--] [<path>...]
   or: git submodule [--quiet] foreach [--recursive] <command>
   or: git submodule [--quiet] sync [--recursive] [--] [<path>...]
CMake Error at CMakeLists.txt:442 (message):
  git failed with exit code 1


-- Configuring incomplete, errors occurred!
See also "/tmp/gencmpclient/CMakeFiles/CMakeOutput.log".

**Comment by DDvO** [comment]
> _Originally posted by @DDvO in [#221 (comment)](https://github.com/mpeylo/cmpossl/issues/221#issuecomment-948725567)_
> 
> hello DDvO, i don`t find the cmp-lib4

Those hints and workarounds of October 2021 are outdated.
For current instructions how to build this library, see its [README](../).
Thus, good that you instead now use, e.g., `cmake .`

**Comment by DDvO** [comment]
> when i use cmake . , an error is reported
> 
> [pp@/tmp/gencmpclient]$ cmake . -- The C compiler identification is GNU 4.8.5 

This (GCC?) compiler version appears extremely old.

> -- generic CMP client version 2.0

So actually you build in the context of the genCMPClient -
this issue would have better been placed in that project.
Anyway,

>  -- using OpenSSL package, with version 1.0.2k

Your build is attempting to use a heavily outdated version of OpenSSL.
This is insecure and from both the OpenSSL and genCMPClient perspective unsupported.
This most likely is also the reason for your build issue #243.
 
You really should use at least OpenSSL 3.0.

> -- fetching git submodule libsecutils
>  usage: git submodule ..

Looks like you are also using an old version of `git`.

Please refer to the [README of the genCMPClient](https://github.com/siemens/gencmpclient) which versions of OpenSSL and build tools are supported/tested.

**Comment by DDvO** [comment]
What do you get as output of `git --version` ?

Please try entirely commenting out (or deleting) the following line from `CMakeLists.txt` in the `gencmpclient` main directory:
```
set(GIT_DEPTH --depth 1) # used to speed up getting submodules
```
Does this fix for you the above `cmake` issue?

**Comment by DDvO** [comment]
@1042198949 the `git submodule` issue, likely due to non-support by an old version, should now be fixed.
