### ISSUE TITLE
Move creation of transactionID to from cmp_lib.c to cmp_ctx.c

### ISSUE THREAD

**Issue by tpank** [mpeylo/cmpossl#31]
The transaction ID shouldn't be created (from random) while from CMP_PKIHEADER_init(), but rather through a context setting. The current way of events is somewhat non-natural.

This should then give more control to the API user to do  all of the following from RFC 4210 - if ever needed:
   
   The transactionID field within the message header is to be used to
   allow the recipient of a message to correlate this with an ongoing
   transaction.  This is needed for all transactions that consist of
   more than just a single request/response pair.  For transactions that
   consist of a single request/response pair, the rules are as follows.
   A client MAY populate the transactionID field of the request.  If a
   server receives such a request that has the transactionID field set,
   then it MUST set the transactionID field of the response to the same
   value.  If a server receives such request with a missing
   transactionID field, then it MAY set transactionID field of the
   response.

This will need changes to of CMP_CTX_set1_transactionID() and CMP_PKIHEADER_set1_transactionID().

Reported by: mpeylo

Original Ticket: [cmpforopenssl/bugs/34](https://sourceforge.net/p/cmpforopenssl/bugs/34)

**Comment by DDvO** [comment]
Meanwhile, `CMP_PKIHEADER_set1_transactionID()` has been replaced by `CMP_ASN1_OCTET_STRING_set1()`, which does not have the memory leak mentioned above.

**Comment by DDvO** [comment]
Martin, I suggest closing this issue as fixed/obsolete.
