### ISSUE TITLE
Validate and overwork how subject/alt/names are set in certreq_new()

### ISSUE THREAD

**Issue by tpank** [mpeylo/cmpossl#33]
The logic how subjectName and subjectAltNames are set from ctx->subject, ctx->subjectAltNames and ctx->clCert and ctx->oldClCert must be overworked for IR, CR, and KUR.

The logic must be properly documented.

Reported by: mpeylo

Original Ticket: [cmpforopenssl/bugs/36](https://sourceforge.net/p/cmpforopenssl/bugs/36)

**Comment by DDvO** [comment]
fix including documentation done; to be reviewed
