### ISSUE TITLE
HTTP proxy option does not work for TLS connections

### ISSUE THREAD

**Issue by tpank** [mpeylo/cmpossl#52]
At least for the proxy I'm using within our intranet, HTTP connections to external servers (like the Insta Demo CA) work fine, but on HTTPS connection attempts to any TLS servers I get: 

2147483704:error:140E0197:SSL routines:SSL_shutdown:shutdown while in init:ssl/ssl_lib.c:1880:
2147483704:error:350A2089:CMP routines:CMP_PKIMESSAGE_http_perform:failed to receive pkimessage:crypto/cmp/cmp_http.c:389::SSL routines:SSL_shutdown:shutdown while in init

Reported by: DDVO

Original Ticket: [cmpforopenssl/bugs/55](https://sourceforge.net/p/cmpforopenssl/bugs/55)

**Comment by mpeylo** [comment]
done
